language: rust
cache: cargo
sudo: false
rust:
  - 1.17.0 # oldest version supported
  - stable
  - nightly

matrix:
  allow_failures:
    - rust:
      - nightly

before_script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo install rustfmt --force &&
      cargo install clippy --force;
    fi

script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo fmt -- --write-mode=diff &&
      cargo clippy;
    fi
  - cargo build --verbose
  - cargo test --verbose
